dir_path = {
  'dir1': 'schema_packages.steps.add.synthesis.CVD.ICP_CVD',
  'dir2': 'schema_packages.steps.add.synthesis.coating.Spin_Coating',
  'dir3': 'schema_packages.steps.transform.lithography.ebl.EBL',
  'dir4': 'schema_packages.steps.transform.lithography.fib.FIB',
  'dir5': 'schema_packages.steps.remove.etching.dry_etching.ICP_RIE',
  'dir6': 'schema_packages.steps.remove.etching.wet_etching.WetCleaning',
  'dir7': 'schema_packages.steps.remove.developing.development.ResistDevelopment',
  'dir8': 'schema_packages.steps.add.integration.bonding.Bonding',
  'dir9': 'schema_packages.steps.transform.thermal_process.annealing.Annealing',
#  'dir10': 'schema_packages.steps.transform.LTODensification',
  'dir11': 'schema_packages.steps.transform.thermal_process.oxidation.ThermalOxidation',
  'dir12': 'schema_packages.steps.transform.dicing.dicing.Dicing',
#  'dir13': 'schema_packages.steps.transform.Doping',
  'dir14': 'schema_packages.steps.transform.lithography.labeling.LabelingCleaning',
#  'dir15': 'schema_packages.steps.transform.SOD',
#  'dir16': 'schema_packages.steps.transform.Track',
  'dir17': 'schema_packages.steps.add.synthesis.electron_gun.ElectronGun',
  'dir18': 'schema_packages.steps.add.synthesis.sputtering.Sputtering',
  'dir19': 'schema_packages.steps.add.synthesis.sog.SOG',
  'dir20': 'schema_packages.steps.remove.etching.dry_etching.RIE',
  'dir21': 'schema_packages.steps.remove.etching.wet_etching.WetEtching',
  'dir22': 'schema_packages.steps.remove.etching.stripping.Stripping',
  'dir23': 'schema_packages.fabrication_utilities.ObservationMeasurements',
  'dir24': 'schema_packages.fabrication_utilities.StartingMaterial',
  'dir25': 'schema_packages.steps.transform.thermal_process.baking.Baking',
  'dir26': 'schema_packages.steps.remove.etching.dry_etching.DRIE_BOSCH',
  'dir27': 'schema_packages.steps.add.synthesis.CVD.PECVD',
  'dir28': 'schema_packages.steps.add.synthesis.CVD.LPCVD',
  'dir29': 'schema_packages.steps.remove.developing.development.SpinResistDevelopment',
  'dir30': 'schema_packages.steps.remove.drying.drying.Rinsing_Drying',
  'dir31': 'schema_packages.steps.add.synthesis.coating.Coating',
}
